name: DC-CustomItems
version: 1.322.0
main: me.dcplugin.dcustomitems.Main
api-version: '1.21'
description: Modular custom items plugin with Java API
author: animesao

softdepend:
  - PlaceholderAPI
  - Vault

commands:
  customitems:
    description: Reload plugin
    usage: /customitems reload
    aliases: [ci]
    permission: dcustomitems.reload

permissions:
  dcustomitems.reload:
    description: Reload plugin
    default: op
